### ISSUE TITLE
Allow omitting param documentation without showing bold "Not Documented"

### ISSUE THREAD

**Issue by menewman** [GraphiDocsOrg/docs#29]
![Screen Shot 2019-03-22 at 3 25 08 PM](https://user-images.githubusercontent.com/747378/54856344-4745e580-4cb7-11e9-9b81-48d976c7971f.png)

^Something about the bold `[Not documented]` here feels like a rebuke to me. 😅 In general it's good to document all fields, but in some cases (like the screenshot's example) the meaning of a param may be very obvious and okay to omit. As a result, if documentation is missing for parameters, it would be nice to simply show something like this:

```graphql
# Query a company by ID.
company(id: ID!): Company
```

That way we don't have to write very redundant docstrings that look like this:
```graphql
  """
  Query a company by ID.
  """
  company(
    """
    The ID of the company to query.
    """
    id: ID!
  ): Company
```

...or generate documentation that looks incomplete, especially if it will be shared externally. (If it's for our own internal dev team then it's probably okay!) For now, redundant docstrings seem to be the way to go, but it would be nice to just omit undocumented params entirely so that they don't stand out so much.

Complications:
What to do if some params are omitted and others are not? In that case, maybe just show the name without anything else?
```graphql
# Query a company by ID.

# Arguments
# id
# someOtherArg: This is an additional argument with some purpose. 
company(id: ID!, someOtherArg: SomeOtherType): Company
```

Or omit the undocumented ones?
```graphql
# Query a company by ID.

# Arguments
# someOtherArg: This is an additional argument with some purpose. 
company(id: ID!, someOtherArg: SomeOtherType): Company
```

Or just show something slightly less obtrusive that isn't in bold?
```graphql
# Query a company by ID.

# Arguments
# id: -
# someOtherArg: This is an additional argument with some purpose. 
company(id: ID!, someOtherArg: SomeOtherType): Company
```

**Comment by mitchellsimoens** [comment]
Hey sorry, just noticed this issue. Had a production release this week so it was crunch time in March. I'll be taking a look at this hopefully this weekend but may be early next week!

**Comment by mitchellsimoens** [comment]
I'm going to be releasing 1.0.6 soon. I made two changes:

1. Just removed the description but kept the args listed above
2. Reason I kepts the args listed even when there is no description is because it looked incomplete and I only bold the arg name if it is required. Here is an example:

![Screen Shot 2019-04-11 at 8 25 55 AM](https://user-images.githubusercontent.com/325473/55957882-65a75d00-5c35-11e9-82e7-7d53642a645d.png)

Here, the `state` argument is required so it's bold but has no description. The `userId` argument is option so not bold but is showing it's description.

**Comment by menewman** [comment]
Thank you, @mitchellsimoens! I think the reasoning behind that implementation makes sense.

I might contend that the name/presence of the argument and its typing already convey all the information that bolding/including the arg without a description do, but it's really not a big deal and I think this looks a lot more friendly than the previous version either way.
