### ISSUE TITLE
Remove bluebird usages with native promise

### ISSUE THREAD

**Issue by mitchellsimoens** [GraphiDocsOrg/docs#3]

**Comment by gavinhenderson** [comment]
@mitchellsimoens Ill hold off doing this until you have completed the cleanup task so i don't duplicate any changes

**Comment by mitchellsimoens** [comment]
Once I hear back from @cabello about that PR I'll merge. Don't want to start off on the wrong foot :)

**Comment by cabello** [comment]
We are all good :)

**Comment by gavinhenderson** [comment]
@mitchellsimoens Do you want bluebird dependency removed completely or just when its used as a Promise? `Bluebird.promisfy` is used multiple times, but if you want I can change that to `util.promisify`?

**Comment by mitchellsimoens** [comment]
@gavinhenderson my thought is unless Bluebird is giving something special that we cannot do with native promises (or `util.promisify`), then we don't need it. So if we can replace with something native we are good. Plus we are using Typescript which can compile down so definitely no need for Bluebird.
