### ISSUE TITLE
Line Numbers all 2

### ISSUE THREAD

**Issue by jicee13** [GraphiDocsOrg/docs#30]
Something I noticed in the docs I've been generating for myself and also on the examples is that all the line numbers are `2`. Wasn't sure if this was a known issue? It would be great to be able to send links to the direct line numbers.

https://graphidocsorg.github.io/docs/star-wars/field.spec.html#L2

**Comment by mitchellsimoens** [comment]
Thanks for reporting! Think I found the bug and released a 1.0.5 version that should fix this. I'll be updating GitHub pages here shortly. I'll leave this issue open if you get a chance to take a look on your end (or I'll close in a week or so).

**Comment by mitchellsimoens** [comment]
Here is an example: https://graphidocsorg.github.io/docs/packages/docs/examples/github/query.doc.html#L55

**Comment by jicee13** [comment]
Great thanks! Just updated and all worked well.
