### ISSUE TITLE
Support to triple quote strings

### ISSUE THREAD

**Issue by cabello** [GraphiDocsOrg/docs#6]
Issue from parent repo: https://github.com/2fd/graphdoc/issues/64

We use https://github.com/rmosolgo/graphql-ruby and they moved from `#` comments to `"""` strings when dumping the IDL file. Generating documentation is currently breaking due to that change.

**Comment by fangel** [comment]
This is because a really old version of the GraphQL library is used. Another fork of the project fixed it by bumping the version:
https://github.com/zzak/graphdoc/commit/dc78ebf8f12d836ad977a02a4a8cff5ddabb2e97
